# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(max_length=255)),
                ('line3', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
